version: '3.6'

services:
  db:
    image: postgres:10.10
    volumes:
      - postgres:/var/lib/postgresql/data
  app: &app
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - bundle:/bundle
      - .:/home/app/webapp
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bash -c "sleep 1000000"
  worker:
    <<: *app
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
volumes:
  bundle:
  postgres:
